### ISSUE TITLE
is there a way to mirror multiple registries

### ISSUE THREAD

**Issue by chenzhiwei** [containers/image#1341]
I did find solution from doc: https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md

My use case is: I have mirrored three different registries and want to set them in registries.conf file.

```
registry:
- prefix: docker.io/first
  mirrors: [local.repo/first]
- prefix: quay.io/second
  mirrors: [local.repo/second]
- prefix: gcr.io/third
  mirrors: [local.repo/third]
```

Is there a way to set above in registries.conf file? Thanks in advance.
