### ISSUE TITLE
support registry mirrors

### ISSUE THREAD

**Issue by vrothberg** [containers/image#397]
Currently, we are working on adding support for private-registry mirrors to moby/docker (see https://github.com/moby/moby/pull/34319). The core semantics are that users can specify mirrors for a given registry, which will be selected as endpoints prior to the registry when pulling an image. Prior to our change, mirroring worked only for the docker hub.

The ability to mirror registries (i.e., pull-through caches) has various use-cases and has been requested to moby/docker upstream for a long while. It is likely that once https://github.com/moby/moby/pull/34319 is merged, to face an increasing demand for a mirror feature beyond moby, but for tools using the `containers` libraries (e.g., skopeo, podmon, cri-o). _Hence, I want to kick off a discussion and ask for feedback and ideas if there is interest to support registry mirrors in `containers/image` and how it should be implemented._

One possibility could be to extend https://github.com/containers/image/blob/master/pkg/sysregistries/system_registries.go#L24 with a mapping `registry -> [mirrors]` in the tomlconfig that can be used during endpoint/refSrc lookup.

Cc: @mtrmac
Cc: @cyphar 
Cc: @flavio

**Comment by mtrmac** [comment]
It does sound interesting, and `pkg/sysregistries` does look like the natural place to keep the configuration.

(It is a bit annoying that we anticipate having two separate configuration locations from the outset, but, oh well, it’s only like the millionth time :) )

**Comment by vrothberg** [comment]
@rhatdan @mtrmac Thanks for your comments!

Currently, there is a clear separation between secure and insecure registries in `pkg/sysregistries`. While the most straight-forward way of supporting mirrors might be adding another `[mirrors]` table, I am not sure if that's the most elegant one.
I see some beauty the way https://github.com/moby/moby/pull/34319 configures Docker's `daemon.json`. Now, there's an array of `Registry` structs, where the `URL`'s scheme determines if it's a secure (`https`) registry or an insecure (`http`) one. Each registry has an optional array of mirrors, with the same URL semantics as registries.

I wonder if we can achieve something similar for `pkg/sysregistries` as exemplified in the snippet below. As far as I can see, such a change would still be backwards compatible. What's your take on this?

```toml
[[registry]]
  url = "http://insecure.registry.com"

[[registry]]
  url = "https://blocked.registry.com"
  blocked = true

[[registry]]
  url = "https://secure.registry.com"

  [[registry.mirror]]
    url = "https://mirror1.secure.registry.cm"

  [[registry.mirror]]
    url = "https://mirror2.secure.registry.cm"
```

Cc: @cyphar, @runcom
